#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
config="$repo_root/NeuralAmpModeler/config.h"
implementation="$repo_root/NeuralAmpModeler/NeuralAmpModeler.cpp"

grep -q '^#define PLUG_WIDTH 1200$' "$config"
grep -q '^#define PLUG_HEIGHT 520$' "$config"
grep -q '^#define INTER_REGULAR_FN "Inter-Regular.ttf"$' "$config"
grep -q '^#define INTER_SEMIBOLD_FN "Inter-SemiBold.ttf"$' "$config"
grep -q '"CHANNEL A"' "$implementation"
grep -q '"CHANNEL B"' "$implementation"
grep -q 'attachGlobalStrip' "$implementation"
grep -q '"IN"' "$implementation"
grep -q '"GATE"' "$implementation"
grep -q '"OUT"' "$implementation"
grep -q 'IRECT(24.0f, 18.0f, 56.0f, 58.0f)' "$implementation"
grep -q 'IRECT(85.333f, 23.0f, 101.333f, 55.0f)' "$implementation"
grep -q 'IRECT(130.667f, 18.0f, 162.667f, 58.0f)' "$implementation"
grep -q 'IRECT(192.0f, 18.0f, 224.0f, 58.0f)' "$implementation"
grep -q 'const auto knobSize = 64.0f' "$implementation"
grep -q 'const auto knobControlHeight = 104.0f' "$implementation"
grep -q 'const auto knobSpacing = 99.0f' "$implementation"
grep -q 'kNoiseGateActive, "", style, true' "$implementation"
grep -q 'WithValueText(IText(7.0f, COLOR_WHITE, "Inter-Regular"' "$implementation"
grep -q 'editorBaseColor' "$implementation"
grep -q 'stripColor' "$implementation"
grep -q 'channelAPanelColor' "$implementation"
grep -q 'channelBPanelColor' "$implementation"
grep -q 'LoadFont("Inter-Regular", INTER_REGULAR_FN)' "$implementation"
grep -q 'LoadFont("Inter-SemiBold", INTER_SEMIBOLD_FN)' "$implementation"
grep -q 'DualNAMVectorKnob' "$implementation"
grep -q 'DualNAMVectorSwitch' "$implementation"
grep -q 'DualNAMSegmentMeterControl' "$implementation"
grep -q 'IRECT(10.0f, 10.0f, 1190.0f, 70.0f)' "$implementation"
grep -q 'IRECT(10.0f, 450.0f, 1190.0f, 510.0f)' "$implementation"
grep -q 'IRECT(606.0f, 80.0f, 1191.0f, 440.0f)' "$implementation"
grep -q 'globalInputLabelArea' "$implementation"
grep -q 'gateToggleArea' "$implementation"
grep -q 'attachChannelPanel' "$implementation"
grep -q 'kModelAOutputLevel' "$implementation"
grep -q 'kModelBOutputLevel' "$implementation"
grep -q 'kCtrlTagInputMeterB' "$implementation"
grep -q 'kCtrlTagOutputMeterB' "$implementation"
grep -q 'kModelAEQActive' "$implementation"
grep -q 'kModelBEQActive' "$implementation"
grep -q '"EQ_A_KNOBS"' "$implementation"
grep -q '"EQ_B_KNOBS"' "$implementation"
! grep -q 'settingsButtonArea' "$implementation"
! grep -q 'new NAMCircleButtonControl' "$implementation"
! grep -q 'new NAMSlimOverlayBackdropControl' "$implementation"
! grep -q 'meterBackgroundBitmap' "$implementation"

echo "DualNAM UI layout tests passed"
