#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
config="$repo_root/NeuralAmpModeler/config.h"
implementation="$repo_root/NeuralAmpModeler/NeuralAmpModeler.cpp"

grep -q '^#define PLUG_WIDTH 1200$' "$config"
grep -q '^#define PLUG_HEIGHT 520$' "$config"
grep -q '^#define INTER_REGULAR_FN "Inter-Regular.ttf"$' "$config"
grep -q '^#define INTER_SEMIBOLD_FN "Inter-SemiBold.ttf"$' "$config"
grep -q '^#define DUALNAM_BOARD_FN "DualNAM-Board.svg"$' "$config"
grep -q '^#define DUALNAM_GLOBAL_STRIP_FN "DualNAM-GlobalStrip.svg"$' "$config"
grep -q '^#define DUALNAM_CHANNEL_A_PANEL_FN "DualNAM-ChannelAPanel.svg"$' "$config"
grep -q '^#define DUALNAM_CHANNEL_B_PANEL_FN "DualNAM-ChannelBPanel.svg"$' "$config"
grep -q '^#define DUALNAM_SELECTOR_BAR_FN "DualNAM-SelectorBar.svg"$' "$config"
grep -q '^#define DUALNAM_METER_LEVEL_FN "DualNAM-MeterLevel.svg"$' "$config"
grep -q '^#define DUALNAM_METER_TRACK_FN "DualNAM-MeterTrack.svg"$' "$config"
grep -q '^#define DUALNAM_METER_SEGMENT_FN "DualNAM-MeterSegment.svg"$' "$config"
grep -q '^#define DUALNAM_KNOB_BLACK_FN "DualNAM-KnobBlack.svg"$' "$config"
grep -q '^#define DUALNAM_KNOB_WHITE_FN "DualNAM-KnobWhite.svg"$' "$config"
grep -q '^#define DUALNAM_SWITCH_ON_FN "DualNAM-SwitchOn.svg"$' "$config"
grep -q '^#define DUALNAM_SWITCH_OFF_FN "DualNAM-SwitchOff.svg"$' "$config"
grep -q '^#define DUALNAM_ARROW_FN "DualNAM-Arrow.svg"$' "$config"
grep -q '^#define DUALNAM_CROSS_FN "DualNAM-Cross.svg"$' "$config"
grep -q '"CHANNEL A"' "$implementation"
grep -q '"CHANNEL B"' "$implementation"
grep -q 'attachGlobalStrip' "$implementation"
grep -q '"IN"' "$implementation"
grep -q '"GATE"' "$implementation"
grep -q '"OUT"' "$implementation"
grep -q 'IRECT(18.0f, 13.0f, 62.0f, 68.0f)' "$implementation"
grep -q 'IRECT(85.333f, 23.0f, 101.333f, 55.0f)' "$implementation"
grep -q 'IRECT(124.667f, 13.0f, 168.667f, 68.0f)' "$implementation"
grep -q 'IRECT(186.0f, 13.0f, 230.0f, 68.0f)' "$implementation"
grep -q 'const auto knobSize = 64.0f' "$implementation"
grep -q 'const auto knobControlHeight = 104.0f' "$implementation"
grep -q 'const auto knobGap = ((outputMeterArea.L - inputMeterArea.R) - (knobSize \* 5.0f)) / 6.0f' "$implementation"
grep -q 'const auto knobSpacing = knobSize + knobGap' "$implementation"
grep -q 'LoadFont("Inter-Regular", INTER_REGULAR_FN)' "$implementation"
grep -q 'LoadFont("Inter-SemiBold", INTER_SEMIBOLD_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_BOARD_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_GLOBAL_STRIP_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_CHANNEL_A_PANEL_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_CHANNEL_B_PANEL_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_SELECTOR_BAR_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_METER_TRACK_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_METER_SEGMENT_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_KNOB_BLACK_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_KNOB_WHITE_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_SWITCH_ON_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_SWITCH_OFF_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_ARROW_FN)' "$implementation"
grep -q 'LoadSVG(DUALNAM_CROSS_FN)' "$implementation"
grep -q 'new ISVGControl(b, dualnamBoardSVG)' "$implementation"
grep -q 'new ISVGControl(stripBounds, dualnamGlobalStripSVG)' "$implementation"
grep -q 'new ISVGControl(panelBounds, panelSVG)' "$implementation"
grep -q 'DualNAMLabeledSVGKnobControl(globalInputArea, globalInputKnobArea' "$implementation"
grep -q 'DualNAMLabeledSVGKnobControl(gateThresholdArea, gateThresholdKnobArea' "$implementation"
grep -q 'DualNAMLabeledSVGKnobControl(globalOutputArea, globalOutputKnobArea' "$implementation"
grep -q 'dualnamKnobWhiteSVG, kInputLevel, "IN"' "$implementation"
grep -q 'dualnamKnobWhiteSVG, kNoiseGateThreshold, "GATE"' "$implementation"
grep -q 'dualnamKnobWhiteSVG, kOutputLevel, "OUT"' "$implementation"
grep -q 'DualNAMSVGSwitchControl(gateToggleArea, kNoiseGateActive' "$implementation"
grep -q 'DualNAMSVGSwitchControl(eqToggleArea, eqActiveParam' "$implementation"
grep -q 'DualNAMSVGMeterControl(inputMeterArea, dualnamMeterTrackSVG, dualnamMeterSegmentSVG)' "$implementation"
grep -q 'DualNAMSVGMeterControl(outputMeterArea, dualnamMeterTrackSVG, dualnamMeterSegmentSVG)' "$implementation"
grep -q 'makeChannelKnob(inputKnobArea, modelInputParam, "Input")' "$implementation"
grep -q 'makeChannelKnob(bassKnobArea, bassParam, "Bass")' "$implementation"
grep -q 'makeChannelKnob(midKnobArea, midParam, "Middle")' "$implementation"
grep -q 'makeChannelKnob(trebleKnobArea, trebleParam, "Treble")' "$implementation"
grep -q 'makeChannelKnob(outputKnobArea, modelOutputParam, "Output")' "$implementation"
grep -q 'dualnamChannelBPanelSVG, dualnamKnobWhiteSVG, COLOR_WHITE' "$implementation"
grep -q 'IRECT(10.0f, 10.0f, 1190.0f, 70.0f)' "$implementation"
grep -q 'IRECT(10.0f, 450.0f, 1190.0f, 510.0f)' "$implementation"
grep -q 'IRECT(606.0f, 80.0f, 1191.0f, 440.0f)' "$implementation"
grep -q 'globalInputLabelArea' "$implementation"
grep -q 'gateToggleArea' "$implementation"
grep -q 'attachChannelPanel' "$implementation"
grep -q 'kModelAOutputLevel' "$implementation"
grep -q 'kModelBOutputLevel' "$implementation"
grep -q 'kCtrlTagInputMeterB' "$implementation"
grep -q 'kCtrlTagOutputMeterB' "$implementation"
grep -q 'kModelAEQActive' "$implementation"
grep -q 'kModelBEQActive' "$implementation"
grep -q '"EQ_A_KNOBS"' "$implementation"
grep -q '"EQ_B_KNOBS"' "$implementation"
! grep -q 'new DualNAMVectorKnob' "$implementation"
! grep -q 'new DualNAMVectorSwitch' "$implementation"
! grep -q 'new DualNAMSegmentMeterControl' "$implementation"
! grep -q 'new ISVGKnobControl' "$implementation"
! grep -q 'settingsButtonArea' "$implementation"
! grep -q 'new NAMCircleButtonControl' "$implementation"
! grep -q 'new NAMSlimOverlayBackdropControl' "$implementation"
! grep -q 'meterBackgroundBitmap' "$implementation"

echo "DualNAM UI layout tests passed"
